Add error handling for missing account info
If you are logged in to Steam but haven't yet browsed a marketplace page you get this error:

TypeError: Cannot destructure property 'language' of 'accountInfoData' as it is undefined.

I propose catching that state and throwing a more helpful error.